#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once 'bootstrap.php';

$console = &$app["console"];

$console->add(new \IZcraft\Command\ListImagesCommand());
$console->add(new \IZcraft\Command\ShowImageCommand());
$console->add(new \IZcraft\Command\PurgeImagesCommand());
$console->add(new \IZcraft\Command\ImageHitCommand());

$console->run();
